# Site settings
title: Coq en Stock
baseurl: "" # begin with /repo-name if use as project, else leave empty for gh-pages
url: "" # default is empty

# Build settings
kramdown:
  input: GFM
  hard_wrap: false
permalink: pretty

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: coqenstock
